# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.7.1/reference/html/application-properties.html#application-properties
# ===================================================================
app:
  id: fraud-detection-simulator
  name: fraud-detection-simulator
  version: 1.0.0-SNAPSHOT
  package: com.luixtech.frauddetection.simulator
  companyName: www.luixtech.com
management: # Management http server configuration, used by ManagementServerProperties
  endpoints:
    web:
      base-path: /management
      exposure: # Refer to https://docs.spring.io/spring-boot/docs/2.7.1/reference/html/application-properties.html#application-properties.actuator
        include:
          - configprops
          - env
          - health
          - beans
          - mappings
          - httptrace
          - shutdown
          - auditevents
          - scheduledtasks
          - loggers
          - prometheus
          - threaddump
  endpoint:
    health: # used by HealthEndpointProperties, Note: it will show health details if it has the access token by Ajax
      enabled: true
      show-details: WHEN_AUTHORIZED
    httptrace:
      enabled: true
    shutdown:
      enabled: true # explicitly enable
  health:
    mail:
      enabled: true
  metrics:
    export:
      prometheus: # Prometheus is the default metrics backend
        enabled: true
        step: 60
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    tags:
      application: ${spring.application.name}
    web:
      server:
        request:
          autotime:
            enabled: true
spring:
  application:
    name: ${app.id}
  profiles:
    # The commented value for `active` can be replaced with valid spring profiles to load.
    # Otherwise, it will be filled in by maven when building the WAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: dev
  banner:
    location: classpath:config/banner-company.txt
  data:
    mongodb:
      auto-index-creation: true
    web:
      pageable:
        one-indexed-parameters: true # whether to expose and assume 1-based page number indexes
        max-page-size: 2000
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
server:
  # It can be overridden by `--server.port` value passed in the commandline or `-Dserver.port` set in `JAVA_OPTS`
  port: 5656
logging:
  level:
    root: INFO
    org.springframework.boot.devtools.autoconfigure: INFO
    org.apache: WARN
    sun.rmi: WARN
    jdk.event.security: WARN
    javax.xml.bind: INFO
    com.zaxxer.hikari.pool.HikariPool: INFO
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: INFO
springdoc: # https://springdoc.org/#migrating-from-springfox
  api-docs:
    enabled: true
  show-actuator: true
  swagger-ui:
    tags-sorter: alpha
# ===================================================================
# Luix framework specific properties
# ===================================================================
luix:
  metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
    logs: # print metrics info to the logs
      enabled: false
      report-frequency: 60 # in seconds
    graphite: # output metrics info to graphite server
      enabled: false
      host: localhost
      port: 2003
      prefix: ${spring.application.name}
  http:
    cache: # Used by the CachingHttpHeadersFilter
      expired-after: 31
  api-docs:
    api-include-pattern: /api/**
    open-api-include-pattern: /open-api/**
    management-include-pattern: /management/**
    api-title: Fraud Detection Simulator API
    open-api-title: Fraud Detection Simulator Open API
    management-title: Fraud Detection Simulator Management API
    version: ${app.version}
    terms-of-service-url:
    contact-name: Louis
    contact-url:
    contact-email: louis@luixtech.com
    license: Unlicensed
    license-url:
  aop-logging:
    enabled: true
    method-whitelist-mode: false
    method-whitelist:
      - AccountController.getTokenUser
  elapsed-time-logging:
    enabled: true
    slow-execution-threshold: 300 # unit: ms
  ribbon:
    # comma separated list of profiles to show a ribbon on the GUI
    display-on-active-profiles: dev,test,demo
# ===================================================================
# Application specific properties
# ===================================================================
application:
  kafka:
    listener:
      input: input
    topic:
      input: input
      rule: rule
      alert: alert
      latency: latency
  input:
    max-input-speed: 50
