name: luix
services:
  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
      - 127.0.0.1:9092:9092
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=lkorDA4qT6W1K_dk0LHvtg
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,INTERNAL://kafka:9094
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LOG_DIRS=/tmp/logs
    healthcheck:
      test: wait-for-port --state=inuse 9092
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 10
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - 127.0.0.1:8084:8080
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9094
    #  redpanda:
    #    image: docker.redpanda.com/redpandadata/console:latest
    #    container_name: redpanda
    #    entrypoint: /bin/sh
    #    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    #    ports:
    #      - 127.0.0.1:8084:8080
    #    environment:
    #      CONFIG_FILEPATH: /tmp/config.yml
    #      CONSOLE_CONFIG_FILE: |
    #        kafka:
    #          brokers: ["kafka:9094"]
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: nc -z localhost 8080 || exit -1
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 10

#  flink-job-manager:
#    image: flink:1.15-java8
#    ports:
#      - 8081:8081
#    command: jobmanager
#    environment:
#      - |
#        FLINK_PROPERTIES=
#        jobmanager.rpc.address: flink-job-manager
#        parallelism.default: 1
#    depends_on:
#      - kafka
#
#  flink-task-manager:
#    image: flink:1.15-java8
#    command: taskmanager
#    environment:
#      - |
#        FLINK_PROPERTIES=
#        jobmanager.rpc.address: flink-job-manager
#        parallelism.default: 2
#    scale: 1
#    links:
#      - "flink-job-manager:jobmanager"  # link to job manager service
#    depends_on:
#      - kafka
#      - flink-job-manager
